SAMPLES = ["a", "b", "c"]


rule all:
    input:
        "results/summary.txt",


rule make_sample:
    output:
        "data/{sample}.txt",
    shell:
        "echo 'sample {wildcards.sample}' > {output}"


rule summarize:
    input:
        expand("data/{sample}.txt", sample=SAMPLES),
    output:
        "results/summary.txt",
    shell:
        "cat {input} > {output}"
